CREATE TABLE IF NOT EXISTS student (
  sl BIGINT PRIMARY KEY AUTO_INCREMENT,
  student_id VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS quiz_result (
  sl BIGINT PRIMARY KEY AUTO_INCREMENT,
  student_id VARCHAR(50) NOT NULL,
  score INT NOT NULL,
  taken_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_result_student FOREIGN KEY (student_id) REFERENCES student(student_id)
);
